{ user, ... }: 
let 
  username = user.username;
in {
  nix.settings.trusted-users = [username];

  users.groups = {
    "${username}" = {};
    docker = {};
    wireshark = {};
    video = {};
    audio = {};
    disk = {};
  };
  # Define a user account. Don't forget to set a password with ‘passwd’.
  users.users."${username}" = {
    # the hashed password with salt is generated by run `mkpasswd`.
    # changeme
    initialHashedPassword = "$6$4g8H.J6lJbq5Mh5S$hU8DwdHk8Rp3ZPdvlkT02eoWnklD.mkCKO3Axue/P4MOkSv9ZiDxp6SriQqTjEKDbtnQBCwQDj3uoc1LCVDrm1";
    home = "/home/${username}";
    isNormalUser = true;
    description = user.fullname;
    extraGroups = [
      username
      "users"
      "video"
      "audio"
      "disk"
      "networkmanager"
      "wheel"
      "docker"
      "wireshark"
      "adbusers"
      "libvirtd"
    ];
    openssh.authorizedKeys.keys = [
    ];
  };
}
